### ISSUE TITLE
No CUDA CPUs available

### ISSUE THREAD

**Issue by mikel2000** [nousr/koi#31]
When I run the last part of the code of koi_colab_backend.ipynb on Google free colab, this error message is shown:

```
RuntimeError                              Traceback (most recent call last)

[<ipython-input-1-d8ad22a0a101>](https://localhost:8080/#) in <module>
     16 pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
     17     "CompVis/stable-diffusion-v1-4", use_auth_token=True
---> 18 ).to("cuda")
     19 
     20 secho("Finished!", fg="green")

6 frames

[/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py](https://localhost:8080/#) in _lazy_init()
    215         # This function throws if there's a driver initialization error, no GPUs
    216         # are found or any other error occurs
--> 217         torch._C._cuda_init()
    218         # Some of the queued calls may reentrantly call _lazy_init();
    219         # we need to just return without initializing in that case.

RuntimeError: No CUDA GPUs are available
```
That's strange, because I can run the pharma SD notebook without problems on free Google colab. This notebook uses CUDA too.

I removed then CUDA from this line and no error occurs.

```
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", use_auth_token=True
)
```

Right now I just started the server, but didn't try to generate an image. So, I'm not sure if this still works after my change.

There are two more places, where CUDA is used:

    torch.cuda.manual_seed(seed)

```
  with autocast("cuda"):
        return_image = pipe(
            init_image=img,
            prompt=headers["prompt"],
            strength=float(headers["sketch_strength"]),
            guidance_scale=float(headers["prompt_strength"]),
            num_inference_steps=int(headers["steps"]),
        )["sample"][0]
```

I have got now three questions:

1. Why isn't it possible to use CUDA although the GPU supports it in general?
2. Will image generation still work after my change described above?
3. How have the code parts posted above to be changed, if CUDA can't be used?

Thanks!

**Comment by nousr** [comment]
hey! have you double checked that you are using a gpu hardware accelertator in colab?

this can be done by going to `Runtime > Change Runtime Type > Accelerator (select GPU)`

---

1. Why isn't it possible to use CUDA although the GPU supports it in general?
    - it is, there is likely a smaller error causing these issues :)
3. Will image generation still work after my change described above?
    - unlikely, and if it will then it will be slow (best to use a gpu)
4. How have the code parts posted above to be changed, if CUDA can't be used?
    - theoretically you should be able to alter the seed method to remove the cuda calls to avoid these issues

**Comment by mikel2000** [comment]
Thank you! That fixed the problem.

**Comment by nousr** [comment]
Hey! Glad you’re having fun. Unfortunately google puts limits on how long you can use their GPU’s for free.Usually the timeout is around 12-24 hours depending. (they change it all the time). You should be able to re-access a gpu tomorrow, for example!On Sep 8, 2022, at 7:25 AM, BlitzAce71 ***@***.***> wrote:﻿
When I go to Runtime > Change Runtime Type > GPU I get this message:
Cannot connect to GPU backend
You cannot currently connect to a GPU due to usage limits in Colab.
And this is after I've used Koi successfully maybe 5-6 times. But now Colab won't use a GPU accelerator and I get the "no CUDA GPUs available" error every time. Which is too bad, because I love this thing!

**Comment by BlitzAce71** [comment]
> 

Thanks for the quick reply, I'll get back at it tonight!
